### ISSUE TITLE
HttpContext.Current not available in outgoing message pipeline

### ISSUE THREAD

**Issue by oliverhanappi** [rebus-org/Rebus#726] opened 2018-08-15 09:03 UTC
Rebus 4.2 switched to using `.ConfigureAwait(false)` in async calls (see commit f1a50e94f1a1624512e83fbcc62464d767ef3ac1). This causes HttpContext.Current to be not available within outgoing steps of the outgoing message pipeline because HttpContext.Current unfortunately does not flow across async calls using the logical call context or AsyncLocals but a special AspNetSynchronizationContext. Obviously, the same issue may happen for anything else which flows by using a synchronization context.

While it is in general advisable for library authors to use `.ConfigureAwait(false)` within their own library if their own code does not depend on any synchronization context, this does not hold true anymore if there are extension points where non-library code may be executed as well.

Please note that this issue is very subtle. We had Rebus configured with type based routing and subscriptions stored centrally in SQL Server. On send operations HttpContext.Current was available in outgoing steps because the type based routing effectively runs synchronously albeit the interfaces being asynchronous. On publish operations on the other hand HttpContext.Current was not available anymore in outgoing steps because the destination addresses where looked up in SQL Server asynchronously first, causing the thread to change.

We were able to store HttpContext.Current within an AsyncLocal prior to invoking Rebus and accessing the HttpContext from there, however it would be nice if we would not need to resort to such workarounds.

We suggest to not use `.ConfigureAwait(false)` across the entire library but only at places where no non-library code may be executed afterwards in order to mitigate such issues.

**Comment by mookid8000** [comment] 2018-08-15 15:59
Hmm, I see. That's pretty fucking annoying, because I have ALWAYS been the one saying

> "Why, silly people, do you type that `.ConfigureAwait(false)` thing all the time?"

and then people would go

> "Because: Performance! You should ALWAYS use `.ConfigureAwait(false)` when you're a library author."

and I have usually replied with

> "I am not sure I fully understand the implications of this. And you cannot explain it properly to me."

and people would say

> "Performance! You should ALWAYS use `.ConfigureAwait(false)` when you're a library author."

and I would usually refuse. But then, at some point, someone got me convinced anyway, and I went and changed it.

I understand now what the problem is! And the problem gets even more real in Rebus, because you are pretty much encouraged to extend Rebus by either a) inserting steps into its (very async) pipelines, or b) decorating its (primarily async) services.

This also means that almost any async call in Rebus to one of its [abstractions](https://github.com/rebus-org/Rebus/wiki/Extensibility#abstractions) can hit a user-provided decorator and thus potentially be a callback to user code that expects a proper execution context to be there.

My own conclusion at this point is that `.ConfigureAwait(false)` in Rebus should be outright banned.

How does that sound to you?

**Comment by oliverhanappi** [comment] 2018-09-06 06:55
Would you mind if we create a pull request which removes the `ConfigureAwait(false)` calls and is there anything we should be aware of when doing so? We would probably target 4.x because 5.x is not released yet.

**Comment by mookid8000** [comment] 2018-09-06 07:45
it would be cool if you did 😄 

if you fork and PR against the release/4 branch I will ensure it gets into the 5 version as well

**Comment by oliverhanappi** [comment] 2018-09-16 14:18
Hi @mookid8000, unfortunately we had no sparse time to make the change yet because we are currently on a project with a pretty tight timeline. As a workaround we downgraded to Rebus 4.1 for the moment.

If it is acceptable for you to wait a few more weeks for the PR, we can still do it. However if you are going ahead and make the change, we will be very happy to upgrade Rebus to the new version 😄

**Comment by mookid8000** [comment] 2018-09-19 08:44
Fixed by #736 which is out in Rebus 4.2.2

(I will merge to the Rebus 5/master track soon)

**Closed by mookid8000** 2018-09-19 08:44 UTC
Labels: +++, Backlog

**Comment by mookid8000** [comment] 2018-09-26 12:56
Fixed in Rebus 5.0.0-b19 too

**Comment by SimonCropp** [comment] 2021-02-04 00:33
as an aside, it is now recommended to use [IHttpContextAccessor](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context) to get access to the http context

**Comment by mookid8000** [comment] 2021-02-04 06:04
@SimonCropp good point! When using Rebus together with Rebus.ServiceProvider, your current `IServiceProvider` will be accessible via the `OutgoingMessageContext` of the outgoing step, this way providing a way to retrieve `IHttpContextAccessor` and this way get the current HTTP context.
