### ISSUE TITLE
when used UseInMemoryTransport, the post is published twice

### ISSUE THREAD

**Issue by dimkadv2** [rebus-org/Rebus#974] opened 2021-06-07 18:45 UTC
Hi!

when used UseInMemoryTransport, the post is published twice

```c#
            builder.RegisterRebus((configurer, context) =>
            {
                var queueName = "queue";
                var subscriberStore = new InMemorySubscriberStore();
                var inMemNetwork = new InMemNetwork(true);

                configurer
                    .Logging(l => l.ColoredConsole())
                    .Transport(x => x.UseInMemoryTransport(new InMemNetwork(true), queueName))
                    .Subscriptions(s => s.StoreInMemory(new InMemorySubscriberStore()))
                    .Options(x =>
                    {
                        x.SetMaxParallelism(1);
                        x.SimpleRetryStrategy(maxDeliveryAttempts: int.MaxValue);
                    });

                return configurer;
            });

            builder.RegisterHandlersFromAssemblyOf<ControllerChangeMessageHandler>();

            builder.RegisterBuildCallback(c =>
            {
                var bus = c.Resolve<IBus>();
                var messageTypes = AssemblyHelpers.GetImplementations(typeof(IHandleMessages))
                    .SelectMany(x => x.GetInterfaces())
                    .Where(x => x.IsGenericType && x.GetGenericTypeDefinition() == typeof(IHandleMessages<>))
                    .SelectMany(x => x.GetGenericArguments())
                    .Where(x => typeof(RebusMessage).IsAssignableFrom(x))
                    .ToList();

                foreach (var messageType in messageTypes)
                {
                    bus.Subscribe(messageType).GetAwaiter().GetResult();
                }
            });
```

and when I post a message, I see the following text in the console:

```
[DBG] Rebus.Pipeline.Send.SendOutgoingMessageStep (Thread #10): Sending Rbu.API.Services.Messages.ControllerChangeMessage -> "queue"
[INF] Rebus.Transport.InMem.InMemNetwork (Thread #10): 6633b476-618d-4853-a98e-91ab60117900 ---> queue (In-mem network 2)
[INF] Rebus.Transport.InMem.InMemNetwork (Rebus 1 worker 1): queue ---> 6633b476-618d-4853-a98e-91ab60117900 (In-mem network 2)
```

Please tell me what am I doing wrong?

Thanks in advance!

**Comment by mookid8000** [comment] 2021-06-21 07:47
The lines 
```
1: [INF] Rebus.Transport.InMem.InMemNetwork (Thread #10): 6633b476-618d-4853-a98e-91ab60117900 ---> queue (In-mem network 2)
2: [INF] Rebus.Transport.InMem.InMemNetwork (Rebus 1 worker 1): queue ---> 6633b476-618d-4853-a98e-91ab60117900 (In-mem network 2)
```
indicate that

1: Message with ID `6633b476-618d-4853-a98e-91ab60117900` goes into the queue `queue`
2: Message with ID `6633b476-618d-4853-a98e-91ab60117900` is taken out of the queue `queue`

so it does not look like it is sent twice.

What do you actually mean, when you say that "the post is published twice"?

**Comment by dimkadv2** [comment] 2021-06-21 08:17
Sorry, I wrote incorrectly, I receive messages twice...

**Comment by mookid8000** [comment] 2021-06-21 11:19
As far as I can tell from the log, the message is only received once, as the line with
```
queue ---> 6633b476-618d-4853-a98e-91ab60117900
```
is to be read as "queue named `queue` has delivered message with ID `6633b476-618d-4853-a98e-91ab60117900` to a Rebus instance"

How do you see that the message is received twice?

**Comment by dimkadv2** [comment] 2021-06-29 17:28
Hi
After starting the application, I publish message:
```c#
await bus.Publish(new SetControllerVariableMessage());
```

the handler looks like this:

```c#
    public class SetControllerVariableMessageHandler : IHandleMessages<SetControllerVariableMessage>
    {
        public Task Handle(SetControllerVariableMessage message)
        {
            System.Console.WriteLine("Hello world");

            return Task.CompletedTask;
        }
    }

```
When I run the application, I see the following in the console:
```
[DBG] Rebus.Pipeline.Receive.DispatchIncomingMessageStep (Thread #10): Dispatching "Rbu.API.Services.Messages.RequestWorkTableMessage, Rbu.API.Services" "e8b67dfa-069b-4c39-b881-eb533a0311ae" to 2 handlers took 19 ms
[INF] Rebus.Transport.InMem.InMemNetwork (Rebus 1 worker 1): queue ---> b063e7d0-a877-4182-aaef-a80f6640225a (In-mem network 2)
Hello world
Hello world
[DBG] Rebus.Pipeline.Receive.DispatchIncomingMessageStep (Rebus 1 worker 1): Dispatching "Rbu.API.Services.Messages.SetControllerVariableMessage, Rbu.API.Services" "b063e7d0-a877-4182-aaef-a80f6640225a" to 2 handlers took 1 ms

```
it turns out that the message from the queue was received twice

**Comment by mookid8000** [comment] 2021-07-02 06:54
The text
```
[DBG] Rebus.Pipeline.Receive.DispatchIncomingMessageStep (Thread #10): Dispatching "Rbu.API.Services.Messages.RequestWorkTableMessage, Rbu.API.Services" "e8b67dfa-069b-4c39-b881-eb533a0311ae" to 2 handlers took 19 ms
```
indicates that the message was dispatched to 2 handlers. It looks like your service provider is returning the same handler twice, when resolving handlers for your message.

Did you register your handler type twice?

**Comment by dimkadv2** [comment] 2021-07-02 09:17
no, i don't register my subscription twice,

registering a handler is as follows:
```c#
builder.RegisterHandlersFromAssemblyOf<ControllerChangeMessageHandler>();
```

subscriptions:

```c#
            var bus = lifetimeScope.Resolve<IBus>();
            var messageTypes = AssemblyHelpers.GetImplementations(typeof(RebusMessage))
                .ToList();

            foreach (var messageType in messageTypes)
            {
                await bus.Subscribe(messageType);
            }

            bus.Advanced.Workers.SetNumberOfWorkers(1);
```

**Comment by mookid8000** [comment] 2021-07-02 09:29
It looks like you're using Autofac - can you confirm that?

Could you maybe try and call
```csharp
var handlers = container.Resolve<IEnumerable<IHandleMessages<SetControllerVariableMessage>>();
```
on the container to see what comes back?

**Comment by dimkadv2** [comment] 2021-07-02 16:14
yes, I got 2 subscribers for this method

How can this error be corrected? strange, I didn't have such problems with a RabbitMq

**Comment by mookid8000** [comment] 2021-07-06 06:34
I've tried to reproduce the issue here: https://github.com/rebus-org/Rebus.Autofac/blob/master/Rebus.Autofac.Tests/Bugs/ReproduceDoubleDispatchIssue.cs

Could you check and see what you are doing that this test does not correctly reproduce?

**Comment by dimkadv2** [comment] 2021-07-06 17:17
Good evening, however, in your version the error was not reproduced, I started looking for the error myself, commented out the registration of handlers, and it turned out that there was already registration, and I made a mistake when automatically registering components in the container. I sincerely apologize for the time wasted!

**Comment by mookid8000** [comment] 2021-07-06 19:01
Ah, no problem! I'm happy to hear that you figured it out 🙂

**Closed by mookid8000** 2021-07-06 19:01 UTC
