### ISSUE TITLE
Azure Service Bus one way client

### ISSUE THREAD

**Issue by ashish051989** [rebus-org/Rebus#717] opened 2018-06-25 12:14 UTC
I'm getting time out while sending message using bus instance as one way client... could you suggest anything on it?

**Comment by mookid8000** [comment] 2018-06-25 12:32
So.... it works fine if you use the same connection string and start your endpoint with an input queue?

**Comment by ashish051989** [comment] 2018-06-25 12:51
Yes..when ever I'm using bus instance without one way client its working fine

**Comment by mookid8000** [comment] 2018-06-25 14:53
Can you show me the exception including the full stacktrace?

**Comment by ashish051989** [comment] 2018-06-25 15:38
Yes, please find below stack trace...

   at Microsoft.ServiceBus.Messaging.SingletonManager`1.EndGetInstance(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.OpenOnceManager.OpenOnceManagerAsyncResult`1.OpenComplete(IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult.AsyncCompletionWrapperCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.OpenOnceManager.Open()
   at Microsoft.ServiceBus.Messaging.MessagingFactory.CreateQueueClient(String path, ReceiveMode receiveMode)
   at Microsoft.ServiceBus.Messaging.QueueClient.CreateFromConnectionString(String connectionString, String path, ReceiveMode mode)
   at Rebus.AzureServiceBus.AzureServiceBusTransport.<GetQueueClient>b__43_0(String address)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Rebus.AzureServiceBus.AzureServiceBusTransport.GetQueueClient(String queueAddress)
   at Rebus.AzureServiceBus.AzureServiceBusTransport.<Send>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.AzureServiceBus.AzureServiceBusTransport.<>c__DisplayClass35_3.<<GetOutgoingMessages>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.AzureServiceBus.Retrier.<Execute>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.AzureServiceBus.AzureServiceBusTransport.<>c__DisplayClass35_2.<<GetOutgoingMessages>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.AzureServiceBus.AzureServiceBusTransport.<>c__DisplayClass35_1.<<GetOutgoingMessages>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Transport.TransactionContext.<Invoke>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Transport.TransactionContext.<RaiseCommitted>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Transport.TransactionContext.<Complete>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Bus.RebusBus.<InnerSend>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Bus.RebusBus.<Send>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Deloitte.Communication.Rebus.MessageBus.CommandBus.<Send>d__12.MoveNext() in C:\SubmissionPlatform\Backend\Dev\Src\Deloitte.Communication.Rebus\MessageBus\CommandBus.cs:line 46

**Comment by mookid8000** [comment] 2018-06-25 18:07
Looks like the stacktrace is missing the exception message... could you maybe post that too?

**Comment by ashish051989** [comment] 2018-06-26 04:36
The exception message is : The Operation has timed out

**Comment by mookid8000** [comment] 2018-06-26 09:58
Ok – so I assume it looks like this:

```
The Operation has timed out
at Microsoft.ServiceBus.Messaging.SingletonManager1.EndGetInstance(IAsyncResult asyncResult) at Microsoft.ServiceBus.Messaging.OpenOnceManager.OpenOnceManagerAsyncResult1.OpenComplete(IAsyncResult result)
at Microsoft.ServiceBus.Common.AsyncResult.AsyncCompletionWrapperCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
at Microsoft.ServiceBus.Messaging.OpenOnceManager.Open()
at Microsoft.ServiceBus.Messaging.MessagingFactory.CreateQueueClient(String path, ReceiveMode receiveMode)
at Microsoft.ServiceBus.Messaging.QueueClient.CreateFromConnectionString(String connectionString, String path, ReceiveMode mode)
at Rebus.AzureServiceBus.AzureServiceBusTransport.b__43_0(String address)
at System.Collections.Concurrent.ConcurrentDictionary2.GetOrAdd(TKey key, Func2 valueFactory)
at Rebus.AzureServiceBus.AzureServiceBusTransport.GetQueueClient(String queueAddress)
at Rebus.AzureServiceBus.AzureServiceBusTransport.d__36.MoveNext()
---
```
To be honest, I still think it looks like some exception messages are missing... but anyways, it looks like Rebus it not able to create the queue client for the destination queue.

Can you tell me some more about what it is you're doing?

Please provide relevant information, e.g. your Rebus configuration, queue names, etc.

**Comment by ashish051989** [comment] 2018-06-26 10:05
So What I'm doing.. I want just to send message from one source say A1.... but that message should get some other consumer say A2... so that's why I sending Message from A1 by using transport as one way client.

Rebus config looks like this:

 var config = Configure.With(adapter)
                .Logging(l => l.Trace())
                .Routing(r => r.TypeBased().MapAssemblyOf<TEvent>(endPoint)); 
if (isOneWayEvent)
            {
                config.Transport(t => t.UseAzureServiceBusAsOneWayClient(ServiceBusConnectionString, AzureServiceBusMode.Standard));
            }
            else
            {
                config.Transport(t => t.UseAzureServiceBus(ServiceBusConnectionString, endPoint, AzureServiceBusMode.Standard));
            }

            var bus = config.Start();

**Comment by mookid8000** [comment] 2018-06-26 10:07
Ok, that looks pretty innocent.

Does it exhibit the same behavior if you create a new Azure Service Bus namespace and use that instead?

**Comment by ashish051989** [comment] 2018-06-26 10:14
New Service Bus namespace... I'm not able to get this

**Comment by ashish051989** [comment] 2018-06-26 10:33
I have tried with couple of Azure Service bus instances...its not working for one way client

**Comment by ashish051989** [comment] 2018-06-26 11:52
Getting same exception with another azure service bus namespace

**Comment by mookid8000** [comment] 2018-06-28 15:00
Ok, I will see if I can get time to investigate this tomorrow. In the meantime, could you maybe show me the line of code that sends the message?

**Comment by ashish051989** [comment] 2018-06-29 06:07
await instance.Send(command);

**Comment by mookid8000** [comment] 2018-06-30 09:17
I can't seem to reproduce the behavior you're seeing. I created a simple console application that looks like this:
```csharp
class Program
{
    const string ConnectionString =
        "Endpoint=(....)";

    static void Main()
    {
        using (var activator = new BuiltinHandlerActivator())
        {
            var gotTheMessage = new ManualResetEvent(false);

            activator.Handle<string>(async str => gotTheMessage.Set());

            Configure.With(activator)
                .Transport(t => t.UseAzureServiceBus(ConnectionString, "receiver"))
                .Start();

            var clientConfigurer = Configure.With(new BuiltinHandlerActivator())
                .Transport(t => t.UseAzureServiceBusAsOneWayClient(ConnectionString))
                .Routing(r => r.TypeBased().Map<string>("receiver"));

            using (var bus = clientConfigurer.Start())
            {
                bus.Send("HEJ MED DIG").Wait();

                if (!gotTheMessage.WaitOne(TimeSpan.FromSeconds(5)))
                {
                    Console.WriteLine("DAMN!!!!!!");
                }
            }
        }
    }
}
```
and it works as expected.

Also, Rebus' transports are pretty well-covered with automated tests, so I would have been pretty surprised if it didn't work.

Could you try the code above and see what happens on your machine?

**Comment by mookid8000** [comment] 2018-07-19 21:02
@ashish051989 hi Ashish, I'm closing this one for now  – please feel free to provide me with more information if you still believe there is a problem 😄

**Closed by mookid8000** 2018-07-19 21:02 UTC
