### ISSUE TITLE
rebus sendlocal fails seemles and loses msg

### ISSUE THREAD

**Issue by AzizDZH** [rebus-org/Rebus#1006] opened 2022-01-14 05:42 UTC
I got such code using rebus and RabbitMq as transport

```
public void Start()
{
_activator = new BuiltinHandlerActivator();
 var bus = Configure.With(_activator)
                        .Logging(l => l.Log4Net())                        
                        )
                        .Transport(t => t.UseRabbitMq(ConnectionString, inputQueue))
                        .Start();
}
```

and Sending procedure

```
public async Task SendMsg()
{
  try
  {
     var DMsg= new DMessage();
     DMsg.someData = "somedata";
     await _serviceBus.SendLocal(DMsg);
  } catch (Exception e)
  {
    log.Error(e);
  }
}
```

But time to time the app loses msgs with no error logged while sending it to bus. The final log I see is from rebus is: **Rebus.Pipeline.Send.SendOutgoingMessageStep [(null)] <(null)> - Sending Messages.DMessage -> "p_messagebus"**

How to avoid this?

**Comment by AzizDZH** [comment] 2022-01-14 12:44
no, but I have another instance of the same app.
you mean that, it was sent to queue and handled by the msg handler?
but in that case there would be logs from handler, but there isn't
Is the rebus log msg "Rebus.Pipeline.Send.SendOutgoingMessageStep ***" means that it was successfully sent, so I should for error in handlers ?

**Comment by mookid8000** [comment] 2022-01-14 12:58
If you have another instance of the same app, then they must be consuming from the same queue, yes? If that's the case, then messages put into the queue will be distributed evenly among the consumers.

E.,g. like this:

![IMG_2564](https://user-images.githubusercontent.com/32968/149518890-620bfd36-737a-4d79-a040-cd5175453291.jpg)

As you can see, messages sent by both instances will be randomly distributed among them, meaning that there's probably a 50% chance that the other instance will be the one to handle the message.

Does it make sense?

**Comment by AzizDZH** [comment] 2022-01-17 03:22
yes, you are right.
each instances handles the message from queue and all steps is logged. Mostly it's working perfect but sometimes It loses msg. the last log is that msg was sent by "sendlocal" and no where handled and not in main queue or error queue. It could be because of rabbit on another server machine and of network issues, but If it's like that why can't catch the exception while sending to queue?

**Comment by mookid8000** [comment] 2022-01-17 07:11
Could you show me your code? Specifically, I am interested in seeing where you send and what your configuration looks like...

**Comment by AzizDZH** [comment] 2022-01-17 10:22
I tried to get all the main parts of code
```
public void Start()
{
	try
	{
		_activator = new BuiltinHandlerActivator();
		_activator.Register(context => new DebitBalanceHandler(context));
		_activator.Register(context => new PaymentMessageHandler());
		
		try
		{
			var bus = Configure.With(_activator)
				.Logging(l => l.Log4Net())
				.Options(o =>
					{
						o.SetNumberOfWorkers(NumberOfWorkerThreads);
						o.SetMaxParallelism(30);
						o.SimpleRetryStrategy(maxDeliveryAttempts:3);
					}
				)
				.Transport(t => t.UseRabbitMq(ConnectionString, inputQueue))
				.Start();
			ServiceBusLocator.SetServiceBus(bus); //store bus reference for use
		}
		catch (Exception e)
		{
			Log.Error(e);
		}
		}
	catch (Exception e)
	{
		Log.Error(e);
		Stop();
	}
	
	
}	
			
public void CreatePayment(PaymentDto paymentDto)			
{
 try
 {
		var DebitBMsg = new DebitBalanceMessage();
		var pmsg = new PaymentMessage();
		pmsg.DateCreated = DateTime.Now;
		pmsg.DebitPart = new PaymentPart();
		pmsg.DebitPart.UserId = paymentDto.Payerid;
		pmsg.DebitPart.UserPhone = paymentDto.PayerPhone;
		pmsg.DebitPart.Amount = paymentDto.DebitAmount.Value;
		await _serviceBus.SendLocal(DebitBMsg);
 }
 catch (Exception e)
 {
	Log.Error(e); 
 }
}
 
    class DebitBalanceHandler : IHandleMessages<DebitBalanceMessage>
    {
        private IMessageContext _messageContext;
        private static readonly ILog Log = LogManager.GetLogger("DebitBalanceHandler.cs");
        private readonly ServiceHelper svc = new ServiceHelper();

        public DebitBalanceHandler(IMessageContext messageContext)
        {
            _messageContext = messageContext;
        }

        public async Task Handle(DebitBalanceMessage message)
        {
            var gatewayList = CacheManager.Instance.GetGatewayProvidersFromCache();
            if (gatewayList == null)
                throw new FailFastException("No Active providers");
            var pmsg = message.PaymentMsg;
            gatewayList = gatewayList.Where(t => t.Id == pmsg.DebitPart.PaymentGatewayId).ToArray();
            if (!gatewayList.Any())
                throw new FailFastException("No Active providers");
            var gatewayDto = gatewayList.First();
            try
            {
                
                if (!CacheManager.Instance.IsGatewayInDeadList(gatewayDto.Id) || Thread.CurrentThread.Name == Utils.VictimThread)
                {
                    var gObj = Utils.CreatePaymentGatewayInstance(gatewayDto, message.PaymentMsg.DebitPart.ServiceCode);
                    var balanceGw = (IBalanceGateway) gObj;
                    await svc.GetPaymentService(ServiceBusLocator.Current, new CacheHelper()).DebitUserBalanceAsync(balanceGw, pmsg, gatewayDto.ClearingType);
                    await ServiceBusLocator.Current.SendLocal((PaymentMessage) message); 
                    await CacheManager.Instance.RemoveGateWayFromDeadListAsync(gatewayDto.Id);
                }
                else
                {
                    throw new FailFastException($"Blame on {gatewayDto.Name} : {gatewayDto.Id} thread name {Thread.CurrentThread.Name}");
                }
            }
            catch (EndpointNotFoundException endEx)
            {
                await CacheManager.Instance.AddGateWay2DeadListAsync(gatewayDto.Id, gatewayDto.Name);
                throw new Exception("Communication problem with " + gatewayDto.Name, endEx);
            }
            catch (Exception e)
            {
                await CacheManager.Instance.AddGateWay2DeadListAsync(gatewayDto.Id, gatewayDto.Name);
                throw;
            }
        }
    }
```

**Comment by mookid8000** [comment] 2022-01-17 11:33
How can this void method `await` the call to `bus.SendLocal`?
```csharp
public void CreatePayment(PaymentDto paymentDto)			
{
 try
 {
		var DebitBMsg = new DebitBalanceMessage();
		var pmsg = new PaymentMessage();
		pmsg.DateCreated = DateTime.Now;
		pmsg.DebitPart = new PaymentPart();
		pmsg.DebitPart.UserId = paymentDto.Payerid;
		pmsg.DebitPart.UserPhone = paymentDto.PayerPhone;
		pmsg.DebitPart.Amount = paymentDto.DebitAmount.Value;
		await _serviceBus.SendLocal(DebitBMsg);
 }
 catch (Exception e)
 {
	Log.Error(e); 
 }
}
```

**Comment by AzizDZH** [comment] 2022-01-18 03:59
sorry made a mistake while shortening the real procedure
```
public async Task CreatePayment(PaymentDto paymentDto)			
{
 try
 {
		var DebitBMsg = new DebitBalanceMessage();
		var pmsg = new PaymentMessage();
		pmsg.DateCreated = DateTime.Now;
		pmsg.DebitPart = new PaymentPart();
		pmsg.DebitPart.UserId = paymentDto.Payerid;
		pmsg.DebitPart.UserPhone = paymentDto.PayerPhone;
		pmsg.DebitPart.Amount = paymentDto.DebitAmount.Value;
		await _serviceBus.SendLocal(DebitBMsg);
 }
 catch (Exception e)
 {
	Log.Error(e); 
 }
}
```
but question is still the same, Is the rebus log msg "Rebus.Pipeline.Send.SendOutgoingMessageStep ***" means that it was successfully sent to queue?

real code is below

```
        public async Task<GatewayResponse> ProcessPaymentByQue(PaymentDto paymentDto, string encryptedUserPass,
            IBalanceGateway balanceGateway)
        {
...
 try
                    {
                        // попытка снятия онлайн 
                        var resp = await DebitUserBalanceAsync(balanceGateway, DebitBMsg.PaymentMsg,
                            debitGatewayDto.ClearingType);
                        resp.Receipt = gresponse.Receipt; // сохраняем номер чека и номер платежа
                        resp.PaymentId = paymentDto.Paymentid;
                        gresponse = resp;
                        // gresponse.Receipt = rr;
                    }
                    catch (Exception e)
                    {
                        Log.Error("Ошибка при онлайн снятии, отправка в кю на доработку:", e);//отправка на снятие в качестве проверки
                        await _serviceBus.SendLocal(DebitBMsg);
                        gresponse.SystemErrorType = SystemErrorType.Ok;
                        gresponse.OperatorSpecificError = gresponse.SystemErrorType.GetDescription();
                        // Log.Error("Ошибка при онлайн снятии, отправка в кю на доработку:", e);
                    }
...
}

  public async Task<GatewayResponse> DebitUserBalanceAsync(IBalanceGateway balanceGw, PaymentMessage balanceMessage,
            string clearingTypeCode = ClearingTypeCodes.BothDebitCredit)
        {
            // непосредственно само снятие
            var balanceResp = balanceGw.DebitAccount(balanceMessage);
            balanceResp.PaymentId = balanceMessage.PaymentId;
            switch (balanceResp.SystemErrorType)
            {
                case SystemErrorType.Ok: // если ответ положительный
                case SystemErrorType.Repeat:
                    balanceMessage.DebitPart.ReferenceId = balanceResp.ReferenceId;
                    if (balanceGw.isIndirect)
                    {
                        Log.Debug(
                            $"Debit first step paymentid:{balanceMessage.PaymentId} userid:{balanceMessage.DebitPart.UserId} got reference:{balanceResp.ReferenceId}");

                        CheckStatusDebitBalanceMessage chMsg = new CheckStatusDebitBalanceMessage();

                        chMsg.PaymentMsg = balanceMessage;
                        try
                        {
                            UpdatePaymentStatus(balanceMessage, PaymentDebitStatus.Accepted, balanceResp.ReferenceId,
                                PaymentStatus.Inprogress, null,
                                balanceResp.OperatorSpecificError,
                                balanceResp.SystemErrorType, "", balanceResp.CardInfo);
                        }
                        catch (Exception e)
                        {

                            Log.Error(e);

                        }

                        await _serviceBus.SendLocal(chMsg);

                    }
                    else
                    {
                        // снятие завершено, сохраняемся
                        Log.Debug(
                            $"Debit succeeded paymentid:{balanceMessage.PaymentId} userid:{balanceMessage.DebitPart.UserId} got reference:{balanceResp.ReferenceId}");
                        if (balanceMessage.PaymentId != null && balanceMessage.PaymentId > 0)
                            try
                            {
                                //получится обновить хорошо нет нестрашно, в кю отправлять не будем
                                UpdatePaymentStatus(balanceMessage, PaymentDebitStatus.DebitSucceeded,
                                    balanceResp.ReferenceId, PaymentStatus.Inprogress, null,
                                    balanceResp.OperatorSpecificError,
                                    balanceResp.SystemErrorType, "", balanceResp.CardInfo);
                            }
                            catch (Exception e)
                            {
                                Log.Error(e);

                            }

                        if (balanceMessage.DebitPart.GatewayType != GatewayTypes.Internal &&
                            balanceMessage.DebitPart.GatewayType != GatewayTypes.FlexCubeBalancing &&
                            (clearingTypeCode == ClearingTypeCodes.BothDebitCredit ||
                             clearingTypeCode == ClearingTypeCodes.CreditOnly))
                        {
                            // отправка на отражение в АБС
                            var smsg = new SettlementMessage();
                            smsg.action = "C";
                            smsg.PaymentMsg = balanceMessage;
                            await _serviceBus.SendLocal(smsg);
                        }

                        //usually it loses the msg here
                        await _serviceBus.SendLocal((PaymentMessage) balanceMessage);
                    }


                    break;
                case SystemErrorType.InsufficientUserBalance:
                case SystemErrorType.Summ:
                case SystemErrorType.InvalidNum:
                case SystemErrorType.InvalidCurrency:
                case SystemErrorType.InvalidRate:
                case SystemErrorType.PaymentNotAllowedForSubscriber:
                case SystemErrorType.GatewayTemporarilyUnavailable:
                case SystemErrorType.InvalidLogin: //невенрый логин пользователя
                    try
                    {
                        Log.Debug(
                            $"Debit account failed {balanceMessage.PaymentId} errortype:{balanceResp.SystemErrorType} desc:{balanceResp.OperatorSpecificError}");
                        UpdatePaymentStatus(balanceMessage,
                            PaymentDebitStatus.ErrorForDebit, balanceResp.ReferenceId, PaymentStatus.ErrorForDebit,
                            null, balanceResp.OperatorSpecificError,
                            balanceResp.SystemErrorType, "", null);

                    }
                    catch (Exception e)
                    {
                        Log.Error(e);
                        //Send msg to update status later.
                        var pmsUpdMsg = new PaymentStatusUpdateMessage();
                        pmsUpdMsg.paymentMessage = balanceMessage;
                        pmsUpdMsg.status = PaymentStatus.ErrorForDebit;
                        pmsUpdMsg.DebitStatus = PaymentDebitStatus.ErrorForDebit;
                        await _serviceBus.SendLocal(pmsUpdMsg);
                        //                        ServiceBusLocator.Current.SendLocal(rmtMsg); todo db update hanler
                    }

                    break;
                default:
                    Log.Debug(
                        $"Debit account inprogress pid:{balanceMessage.PaymentId}  msdesc:{balanceMessage.Desc} errortype:{balanceResp.SystemErrorType} desc:{balanceResp.OperatorSpecificError}");
                    throw new Exception(balanceResp.OperatorSpecificError);

            }

            return balanceResp;


        }

```

**Comment by mookid8000** [comment] 2022-01-18 09:46
>  Is the rebus log msg "Rebus.Pipeline.Send.SendOutgoingMessageStep ***" means that it was successfully sent to queue?

Yes – once `await bus.SendLocal` returns without throwing an exception, it means that the message has been properly delivered.

Could you try running the sender WITHOUT starting the consumer? You can do this by setting number of workers to 0:
```csharp
Configure.With(_activator)
    .(...)
    .Options(o => o.SetNumberOfWorkers(0)) //< 👈 
    .Start();
```

and then go to your RabbitMQ management console (usually `http://localhost:15672`, login with guest/guest) and see if the messages get delivered to the queue as expected every single time?

**Comment by AzizDZH** [comment] 2022-01-19 03:45
It works almost perfect. to apps send/receive about 45000 msgs a day, but sometimes once a month or two few msgs get lost. so I can't simulate it. According your answer and logs I should look more into the handlers because msgs got delivered.

**Comment by mookid8000** [comment] 2022-01-19 06:09
Honestly, I would be very surprised if Rebus somehow lost a message, so I am just trying to narrow down the possibilities here.

If I have understood things correctly, you think that a message was lost, because you are writing to the log both when you send and when you handle each message. Now I understand that we are talking about lots of messages, in the vicinity of 2000 every hour, so that makes me curious: How do you collect the logs? How do you correlate the send/receive statements?

**Comment by AzizDZH** [comment] 2022-01-20 12:30
Correct, I thing the message was lost because when it gots handled it writes log and updates status of payment in the db or sends new msg with different step of processing the payment. if the db update fails it creates another msg just for db update retry. On transaction or payment consist of 2 one by steps each handle and send msgs from/to queue and update the status of it in db. so when we see that the payment in the db stacked on the intermediate status for a log time and there is no msgs in queues (main and error), we start to analyze the logs matching paymentId. 
For now on such cases each time when we look in to the log the last text we see is Rebus.Pipeline.Send.SendOutgoingMessageStep [(null)] <(null)> - Sending ...
So to be sure, I'm going to add debug log at the beginning of the Handle method of the handler class to see if it was called after sending was done.

**Comment by mookid8000** [comment] 2022-01-20 15:41
Hmm it's very very hard for me to understand exactly what you're doing there. 

Just be be sure that Rebus + RabbitMQ works like it's supposed to, I just created an app and let it run for a while. It successfully sent and received several millions of messages without any of them missing, so my guess at this point is that it's something else that somehow results in one of your messages gone missing.

If you can reproduce the lost message scenario in an app that sends and receives a message, then I'd be happy to debug that.

**Comment by mookid8000** [comment] 2022-02-04 12:28
Hi @AzizDZH , after having tested with 100s of millions of messages that I received every single one that I sent, I am closing this issue, as I believe that something else is tricking you somehow.

Feel free to come back to this issue, e.g. if you have additional info about your problem.

**Closed by mookid8000** 2022-02-04 12:28 UTC
Labels: Question
