### ISSUE TITLE
Publisher confirms support with rabbitMq

### ISSUE THREAD

**Issue by hansehe** [rebus-org/Rebus#761] opened 2018-11-20 14:43 UTC
Publisher confirms should be optional to use, and I hope to see it in the next version.

https://www.rabbitmq.com/confirms.html#publisher-confirms

**Comment by mookid8000** [comment] 2018-11-26 08:14
Closing because it's a duplicate of [this](https://github.com/rebus-org/Rebus.RabbitMq/issues/32)

**Closed by mookid8000** 2018-11-26 08:14 UTC
