### ISSUE TITLE
IFailed<Message> handler triggered twice - only one handler registered in Container

### ISSUE THREAD

**Issue by michaeldtaylor** [rebus-org/Rebus#830] opened 2019-09-05 10:56 UTC
I have the following handler in one of my services (this is the simplest version to replicate the issue):

````csharp
public class GenerateProductVariantEventHandler :
    IHandleMessages<GenerateProductVariant>,
    IHandleMessages<IFailed<GenerateProductVariant>>
{
    private static readonly Logger Log = LogManager.GetCurrentClassLogger();

    private readonly IBus _bus;

    public GenerateProductVariantEventHandler(IBus bus)
    {
        _bus = bus;
    }

    public async Task Handle(GenerateProductVariant message)
    {
        throw new ProductVariantGenerationException(message.ProductVariant);
    }

    public Task Handle(IFailed<GenerateProductVariant> messageWrapper)
    {
        Log.Debug("Product variant generation failed. product_variant_name={0}", messageWrapper.Message.ProductVariant);

        return _bus.Publish(new ProductVariantGenerationFailed
        {
            OrderId = messageWrapper.Message.OrderId,
            ErrorDescription = messageWrapper.ErrorDescription
        });
    }
}
````
I have the following configuration:
````csharp
o.SimpleRetryStrategy(maxDeliveryAttempts: 3, secondLevelRetriesEnabled: true);
````
My container only has the following IHandleMessages registrations when populated (modified slightly for clarity):

````
Lifetime = Transient, ServiceType = {Name = "IHandleMessages`1" FullName="Rebus.Handlers.IHandleMessages`1[[GenerateProductVariant]]
Lifetime = Transient, ServiceType = {Name = "IHandleMessages`1" FullName="Rebus.Handlers.IHandleMessages`1[[Rebus.Retry.Simple.IFailed`1[[GenerateProductVariant]]]]
````
When I run the system I see (modified slightly for clarity):
````
Unhandled exception 1 while handling message with ID "9c1446a4-c65c-4df9-9f5d-91ba543c466e"Addr.Portfolio.Domain.Orders.ProductVariantGenerationException: Product variant generation failed   
Unhandled exception 2 while handling message with ID "9c1446a4-c65c-4df9-9f5d-91ba543c466e"Addr.Portfolio.Domain.Orders.ProductVariantGenerationException: Product variant generation failed
Unhandled exception 3 while handling message with ID "9c1446a4-c65c-4df9-9f5d-91ba543c466e"Addr.Portfolio.Domain.Orders.ProductVariantGenerationException: Product variant generation failed
Product variant generation failed. product_variant_name=abcore-fs
Debug SendOutgoingMessageStep: Sending Addr.Portfolio.Domain.Orders.Events.ProductVariantGenerationFailed -> "overlord-queue"
Product variant generation failed. product_variant_name=abcore-fs
Debug SendOutgoingMessageStep: Sending Addr.Portfolio.Domain.Orders.Events.ProductVariantGenerationFailed -> "overlord-queue"
````
So it is hitting the retry limit (3) and then handling IFailed twice. Any idea why it is hitting the handler twice and how to prevent this?

I tried moving the IFailed handling into its own handler, but this actually caused more problems. At the moment this isn't a massive problem as I have an IdempotentSaga in a different service working with the ProductVariantGenerationFailed, but I'd like to understand what I'm doing wrong.

Currently I am using FileSystem transport for test purposes.

Thanks,

Michael Taylor

**Comment by mookid8000** [comment] 2019-09-24 20:08
I've tried to reproduce the behavior you're describing in [this test](https://github.com/rebus-org/Rebus.ServiceProvider/blob/master/Rebus.ServiceProvider.Tests/CheckThisParticularPossibleBug.cs), but I did not succeed.

Could you try and check the code in the test and see where it differs from your code?

Are you by any chance registering the handler twice? If [this line](https://github.com/rebus-org/Rebus.ServiceProvider/blob/master/Rebus.ServiceProvider.Tests/CheckThisParticularPossibleBug.cs#L53) is commented in, then the failed message will seemingly be dispatched twice (but it's actually dispatched only once, it's just being dispatched to two instances of the same handler).

I'm closing this issue for now, because I could not reproduce the issue. Please let me know if you still experience this weird behaviour.

**Closed by mookid8000** 2019-09-24 20:08 UTC

**Comment by michaeldtaylor** [comment] 2020-01-02 17:03
It's been a while, but I've finally had some time to start looking at this again. I ran your test and it worked fine, and I've been trying to get it slightly closer to my code (it's not far off). My code still does not work - I use AutoRegisterHandlersFromAssemblyOf<> and it only has the 2 handlers mentioned before.

The one thing I do is publish from an IdempotentSaga - is there any significant difference between Publish and SendLocal? For me, as soon as the second level gets handled I see 2x HandlerInvokers on the IncomingStepContext. which is Rebus.Retry.FailedMessageWrapper<Addr.Portfolio.Domain.Orders.Messages.GenerateProductVariant>.

I'm using FileSystem transport to test, with JSON and the topics says:

  "Addr.Portfolio.Domain.Orders.Messages.GenerateProductVariant, Addr.Portfolio.Domain": [
    "abcore-cou-generator-queue"
  ]

What is "rbs2-return-address":"overlord-queue"? Does Publish have any special features that aren't replicated in your test?

**Comment by mookid8000** [comment] 2020-01-03 07:37
>  is there any significant difference between Publish and SendLocal?

Not really, no... especially not when you're using the file system transport and JSON to store subscriptions, as "publish" will simply translate into looking up the individual queue names of the subscribers, and then the event will be sent directly to each queue.

> What does "rbs2-return-address":"overlord-queue" do? 

It's so you can
```csharp
await bus.Reply(new SomeReply(...));
```
and have the reply sent back to whoever sent the request.

This is quite puzzling 🙂 maybe you could try and register the handlers manually in Windsor?

Or maybe try and use another IoC container?

Or switch out something else, and see if that makes a difference. If you could succeed in doing that, then it would narrow it down....

**Comment by michaeldtaylor** [comment] 2020-01-03 12:08
Ok, so a stripped my app down to the bare minimum, and you are correct, it is something to do with Rebus and Lamar, but it is only ever an issue when resolving IFailed<> handlers, and only when Rebus is resolving them to use as an invoker. If I resolve it myself like:

````
var failedHandler = host.Services.GetServices<IHandleMessages<IFailed<GenerateProductVariant>>>();
````
Then all is fine - there is only 1 registered.

What I did:

1. Stripped it down to 1 app, with the Saga and Handler in the same place.
2. Tried registering handlers manually myself - makes no difference. Always works in with either AutoRegisterHandlersFromAssemblyOf<> or manually registered in vanilla ServiceProvider (as per your test), and always invokes the IFailed handler twice in the case of Lamar.
3. There is seemingly no issue with normal handlers - they only get invoked once in both.

The main reason I want to use Lamar (or similar) is that it is a superset of ServiceProvider, but allows you to scan and include registries in other assemblies (as per StructureMap). I was using StructureMap before, but then you're sort of fighting ServiceProvider and other container.

There are probably others that act as a superset, but its curious that this is limited to IFailed<> and not general messaging. Could it be a small issue with the Pipeline resolution that only affects Lamar?

**Comment by mookid8000** [comment] 2020-01-03 12:48
Aaah, the plot thickens.... 🙄 which container adapter are you using to hook Rebus up with Lamar?

**Comment by michaeldtaylor** [comment] 2020-01-03 12:53
<PackageReference Include="Rebus.ServiceProvider" Version="4.0.2" />

It seemed to make the most sense based on how Lamar works. As I say, everything else is working, just second level handlers. "host.Services" is IServiceProvider compliant even if it is implemented by Lamar.

**Comment by mookid8000** [comment] 2020-01-03 13:23
Ah, now I get it! Sorry, for being so slow, but I didn't realize that that was how Lamar was implemented.... which I guess is super-neat, actually.

Could you try upgrading to Rebus.ServiceProvider 5.0.0-b06 ? It's much faster, doesn't depend on ASP.NET Core, and it has got an error or two fixed since 4.0.2

**Comment by michaeldtaylor** [comment] 2020-01-03 13:40
If I use 5.0.0-b06 with Lamar and AutoRegisterHandlersFromAssemblyOf<> the last log message I get is: 

Sending Addr.Portfolio.Domain.Orders.Events.OrderReceived -> "overlord-queue" 

Then no handlers get invoked. The handlers are registered in both cases. Does this shed any light?

**Comment by mookid8000** [comment] 2020-01-06 08:16
hmm, not really...... can you see if the same registrations have been made as a consequence of calling `AutoRegisterHandlersFromAssemblyOf`?

**Comment by michaeldtaylor** [comment] 2020-01-06 14:17
Nope, still:

````
            var handlers = host.Services.GetServices<IHandleMessages<GenerateProductVariant>>();
            var failedHandlers = host.Services.GetServices<IHandleMessages<IFailed<GenerateProductVariant>>>();
````

1 of each. I'll have a look through your code and see if I can work out how you resolve services.

**Comment by michaeldtaylor** [comment] 2020-01-06 14:52
Ok, so I saw that you use IServiceProvider. So, trying to get as close to that:

````
var serviceProvider = host.Services.GetService<IServiceProvider>(); // Lamar.Container
            
var handler = serviceProvider.GetService(typeof(IHandleMessages<GenerateProductVariant>));
var failedHandler = serviceProvider.GetService(typeof(IHandleMessages<IFailed<GenerateProductVariant>>));
````
So therefore everywhere in the app that uses IServiceProvider should be resolving the handlers? Unless the resolution of IServiceProvider is different in different places?

**Comment by mookid8000** [comment] 2020-01-06 15:13
hmmm... when Rebus dispatches the failed message, it does so as a `FailedMessageWrapper<TMessage>`, which is Rebus' implementation of `IFailed<TMessage>`.

In your case, that would be `FailedMessageWrapper<GenerateProductVariant>`, which means that this is closer to what is actually happening:
```csharp
var failedHandler = serviceProvider.GetService(typeof(IHandleMessages<FailedMessageWrapper<GenerateProductVariant>>));
```

Could you check that?

**Comment by michaeldtaylor** [comment] 2020-01-06 15:29
I would if FailedMessageWrapper wasn't internal :)

Just to be clear, so as not to conflate different issues with 2 versions of the library, I see the following behaviour:

4.0.2:

1. Normal IMessageHandlers work correctly. IFailed handlers are get invoked twice.
2. FailedMessageWrapper resolution might be a factor in this?

5.0.0-b06

1. No IMessageHandlers are seemingly being invoked at all. The last thing logged is:

Sending Addr.Portfolio.Domain.Orders.Events.OrderReceived -> "overlord-queue" 

Then nothing. No saga gets created.

**Comment by michaeldtaylor** [comment] 2020-01-06 15:51
Just trying to get closer to DependencyInjectorHandlerActivator (v 5.0.0-b06):

````
        private static void DoStuff(IHost host)
        {
            var serviceProvider = host.Services.GetService<IServiceProvider>();
            var scope = serviceProvider.CreateScope();

            var resolvedHandlerInstances = GetMessageHandlersForMessage<GenerateProductVariant>(scope);
            var resolvedErrorHandlerInstances = GetMessageHandlersForMessage<IFailed<GenerateProductVariant>>(scope);
        }
        
        static readonly ConcurrentDictionary<Type, Type[]> _typesToResolveByMessage = new ConcurrentDictionary<Type, Type[]>();
        
        static List<IHandleMessages<TMessage>> GetMessageHandlersForMessage<TMessage>(IServiceScope scope)
        {
            var typesToResolve = _typesToResolveByMessage.GetOrAdd(typeof(TMessage), FigureOutTypesToResolve);

            return typesToResolve
                .SelectMany(type => scope.ServiceProvider.GetServices(type).Cast<IHandleMessages>())
                .Cast<IHandleMessages<TMessage>>()
                .ToList();
        }

        static Type[] FigureOutTypesToResolve(Type messageType)
        {
            var handledMessageTypes = new[] { messageType }.Concat(messageType.GetBaseTypes());

            return handledMessageTypes
                .Select(t => typeof(IHandleMessages<>).MakeGenericType(t))
                .ToArray();
        }
````
Still resolves a single instance for both.

**Comment by michaeldtaylor** [comment] 2020-01-07 12:59
Just in case you have time/are interested I distilled my app down almost as far as it can go to show the problem. This could probably just be another test, but I wanted to show the essence of how simple the problem manifests and make sure that .NET Core 3.1 or other things aren't issues.

In the meantime I will try Autofac instead:

https://github.com/michaeldtaylor/RebusLamar/

**Comment by michaeldtaylor** [comment] 2020-01-07 15:07
So suprise, suprise Autofac works fine:

https://github.com/michaeldtaylor/RebusLamar/tree/feature/autofac

I kept it as similar as possible, swapping Lamar ServiceRegistry for Autofac Module. One thing that initially bit me in Autofac was that IHostedService was getting registered twice. Once sorted, this works as expected. I hoped for a similar problem in Lamar, but no luck. There are only 2x IHostedServices registered.

Looks like I should switch to Autofac for the time being.

**Comment by michaeldtaylor** [comment] 2020-01-10 12:23
On the offchance anyone has this problem in the future, my final solution was to use ServiceProvider directly, use Scrutor for scanning, and then add some custom code to support Registry/Module concept. I prefer this to using Autofac, as all I really wanted was ServiceProvider + extra stuff.

https://github.com/michaeldtaylor/RebusLamar/tree/feature/scrutor/src/Overlord.Other/ServiceProvider

I've asked Scrutor if they might want to include support for modules:

https://github.com/khellang/Scrutor/issues/111

I'd be interested to know what the actual problem was, but its sort of academic now.

**Comment by bosjaH** [comment] 2020-03-13 07:22
Hi,

I'm running into the same issue with Lamar. From my testing, it seems to be somehow related to the usage of interfaces.

```
   public interface ICreateWorkspace
    {
        Guid Id { get; }
    }

    public class CreateWorkspace : ICreateWorkspace
    {
        public Guid Id { get; set; }
    }
```

When my handler implements `IHandleMessages<ICreateWorkspace>`, it gets called twice. When I change it to `IHandleMessages<CreateWorkspace>`, it gets called only once.

Not sure if the issue is with Rebus or Lamar.
