### ISSUE TITLE
timeout exceptions when using azure servicebus

### ISSUE THREAD

**Issue by dampee** [rebus-org/Rebus#428] opened 2016-03-20 00:01 UTC
I get a lot of exceptions when using azure servicebus as transport.  Using 0.99.23 currently.

Any idea where i need to start searching.  

```
20/03/2016 0:55:28 +01:00: System.OperationCanceledException: This messaging entity has already been closed, aborted, or disposed.
   at Microsoft.ServiceBus.Messaging.ClientEntity.ThrowIfClosed()
   at Microsoft.ServiceBus.Messaging.QueueClient.BeginCreateSender(TimeSpan timeout, AsyncCallback callback, Object state)
   at Microsoft.ServiceBus.Messaging.QueueClient.EnsureCreateInternalSender()
   at Microsoft.ServiceBus.Messaging.QueueClient.ThrowIfSenderNull(String operationName)
   at Microsoft.ServiceBus.Messaging.QueueClient.SendAsync(BrokeredMessage message)
   at Rebus.AzureServiceBus.AzureServiceBusTransport.<Send>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.AzureServiceBus.AzureServiceBusTransport.<>c__DisplayClass37_2.<<GetOutgoingMessages>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.AzureServiceBus.Retrier.<Execute>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.AzureServiceBus.AzureServiceBusTransport.<>c__DisplayClass37_3.<<GetOutgoingMessages>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.AzureServiceBus.AzureServiceBusTransport.<>c__DisplayClass37_1.<<GetOutgoingMessages>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Transport.DefaultTransactionContext.<Invoke>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Transport.DefaultTransactionContext.<Commit>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Retry.Simple.SimpleRetryStrategyStep.<DispatchWithTrackerIdentifier>d__8.MoveNext()
```

**Comment by mookid8000** [comment] 2016-03-20 15:44
Weird! I've been using Rebus + Azure Service Bus every day for the last year or so, and I've never seen that exception!

Does it "get over it" afterwards, or does the transport continue to be defective?

**Comment by dampee** [comment] 2016-03-21 12:31
Have had any time to investigate, but I think it has to do with a _bus.Reply(new Message {} );

**Comment by mookid8000** [comment] 2016-03-21 12:39
that sounds weird..! Please let me know what you find out :grimacing:

**Comment by mookid8000** [comment] 2016-04-05 05:08
hi @dampee , did you look some more into this?

**Comment by dampee** [comment] 2016-04-05 06:31
No, just back from Holiday.

hi @dampee<https://github.com/dampee> , did you look some more into this?

-

**Comment by dampee** [comment] 2016-04-18 15:05
We are investigating, but we are not able to pinpoint the error.  Sometimes the error appears, sometimes not.  We are currently running on 0.99.23.
My guts are telling me that it has to do with async related bugs.

**Comment by mookid8000** [comment] 2016-04-18 15:42
Still sounds weird! but please do update to the latest version! I generally only release improvements... 😁

**Comment by mookid8000** [comment] 2016-04-18 18:52
Oh btw., I just remembered something... a colleague of mine experienced timeouts once with Azure Service Bus, and it turned out they were caused by _another tenant_ on Azure! 

You see, Azure Service Bus is (unless you are using the Premium tier, if I understood correctly) just a bunch of shared SQL Server instances, and in this case the other tenant was adding millions of messages at a fierce rate, causing that particular SQL Server instance to constantly throw timeouts back at us when polling for new messages.

Could you try and create a new service bus namespace and see if the problem persists?

**Comment by dampee** [comment] 2016-04-19 07:27
We have found the source of the issue.
The IHandleMessage code being called performs a lot of actions (db, ...), one of the subroutines creates a proxy class which instantiates a new Rebus Adapter, posts a single message and disposes the adapter again.  If we remove this call, everything works flawless.
We can't reuse in the current IBus due to other dependencies.

**Comment by mookid8000** [comment] 2016-04-19 07:45
Excellent! Good you made it work 👌

Sendt fra min iPhone

**Comment by dampee** [comment] 2016-04-19 07:47
Still thinkering on how to solve this.  If I can reproduce the issue in a new solution, would you mind looking further into it?

Kind regards
Damiaan

**Comment by mookid8000** [comment] 2016-04-19 10:57
Oh sorry, maybe I misunderstood you a little bit there... thought you had it completely sorted 😁 

But YES I will be happy to debug it if you can reproduce the issue in a small sample project. In fact I will be very happy if you do that 😄

**Comment by mookid8000** [comment] 2016-04-19 10:57
Let's keep this one open 😄

**Comment by dampee** [comment] 2016-04-21 15:13
Hi,
We were able to reproduce this issue.  We are pushing the solution to a git repo (https://bitbucket.org/dampeebvba/rebus-issue-428).  

We have 2 console line app's. 
* one producer: sends a message every time you hit RETURN.  This console will complain about not being able to process, which is normal.
* one consumer: 
   * First message will be processed fine (we do a modulo 2)
   * Second message will throw an error because we are invoking proxy class sending a new message.  (This is a over simplification of how our solution is setup, but it generates the same issue)

Don't forget, to update the connectionstring in the Common.Constants.

**Comment by mookid8000** [comment] 2016-04-21 21:06
There's a few things going on in that code sample that need to be fixed 😄

**Comment by mookid8000** [comment] 2016-04-21 21:09
1st thing is: All three Rebus instances are using the same input queue as defined by `Constants.Queue` - but that means they will all be competing for the same messages, and each message will only be received by one of them. Granted, the bus instance in the `Proxy` class is almost immediately disposed, so it will most likely not get to receive anything, but you have a `Producer` and a `Consumer` using the same queue, and that will not work the way you want 😁

**Comment by mookid8000** [comment] 2016-04-21 21:10
2nd thing: When `Proxy` sends, it does not wait for the method to complete - the behavior in those cases is pretty hard to predict. I.e. instead of `activator.Bus.SendLocal(message)`, you should `await activator.Bus.SendLocal(message)`

**Comment by mookid8000** [comment] 2016-04-21 21:11
I'll fork the repo and push a few fixes tomorrow 😃

**Comment by mookid8000** [comment] 2016-04-21 21:25
and by "tomorrow" I mean now - [check it out](https://bitbucket.org/mookid8000/rebus-issue-428/src)

**Comment by mookid8000** [comment] 2016-04-21 21:25
there were some things around routing etc that needed fixing too

**Comment by mookid8000** [comment] 2016-04-21 21:26
There's one thing that I still don't understand though: What is the deal with that `Proxy` thing? Why doesn't `MessageDataHandler` just accept an `IBus` injected through its constructor which it can then use to send messages?

**Comment by dampee** [comment] 2016-04-22 10:08
Thanks a lot for your feedback.

> All  three Rebus instances are using the same input queue as defined by Constants.Queue - but that means they will all be competing for the same messages,

Only one solution has handlers.  The rest will post new messages.  It's to extract slow (and process heavy or network) things to other servers.

> you should await activator.Bus.SendLocal(message)

True.  But we can't.  We really can not change this.  Async is contagious.  Our frameworks is not yet 100% async, that would involve at least 10 days of programming (not counting bugs which will be created due to the usage of async)
A best practice when creating async methods, is PostFixing Async to it (cfr entity framework: `.Single()` and `.SingleAsync()`).  Is it possible to have an async AND a non async method?  Please?

> What is the deal with that Proxy thing?

That's a very valid question :-).  At certain points in the business logic we need to trigger events.  It only has to put a message on the bus, so that the event can be processed elsewhere.  The business logic can not have a reference to rebus. Therefor we inject the proxy (or facade) class when we need to trigger an event.

I'll look into the fork you have created this afternoon.

**Comment by dampee** [comment] 2016-04-22 10:13
One more thing: this setup worked in rebus v1 (version 0.83 and lower).

**Comment by mookid8000** [comment] 2016-04-22 10:14
> Only one solution has handlers. The rest will post new messages. It's to extract slow (and process heavy or network) things to other servers.

Then you should configure an input queue only for the bus with handlers, and then let the other buses be of the `*AsOneWayClient(...)` kind.

Otherwise, the other bus instances can snatch a message and then discover that they do not have any handlers to dispatch it to, and then they will return the message to the queue (potentially ending up moving the message to the error queue if it succeeds in receiving the same message 5 times).

**Comment by mookid8000** [comment] 2016-04-22 10:20
> you should await activator.Bus.SendLocal(message)

If you can't `await bus.Send` you should `bus.Send(..).Wait()`

But that can actually end up causing a deadlock if you do it in a handler because of the [problem described here](http://stackoverflow.com/questions/15021304/an-async-await-example-that-causes-a-deadlock).

It is definitely best if you could somehow make an `async` path that allows you to `await`

**Comment by dampee** [comment] 2016-04-22 10:27
> and then let the other buses be of the *AsOneWayClient(...) kind.

how do they know which queue to post too? There is no inputqueue in the `UseAzureServiceBusAsOneWayClient` method? (can't find this in the documentation)

> It is definitely best if you could somehow make an async path that allows you to await

I know, it's work in progress. And it takes us a lot of time to change the code base piece by piece.  We started with all endpoint and are gradually changing the complete codebase...  It's a massive investment.  About the deadlocks: yes i know.  If there is no way to stay away from `async` for now, we might be in deep ******.  If we encounter this in our own codebase, we make a new method `MyMethodAsync` and create a real async version of it, maintaining the two versions.  Just like Entity Framework does too...

**Comment by mookid8000** [comment] 2016-04-22 11:34
> how do they know which queue to post too?

When you use `bus.Send(...)` (i.e. without specifying a destination), you let the bus "route the message". What this means is simply that the bus looks up the message type in its endpoint mappings to see who gets to receive the message.

Endpoints mappings is what you configure when you do this:

    Configure.With(...)
        .(...)
        .Routing(r => {
            r.TypeBased()
                .Map<SomeMessage>("some_queue")
                .MapAssemblyOf<AnotherMessage>("another_queue");
        })
        .Start();

You can read more about it [on the wiki](https://github.com/rebus-org/Rebus/wiki/Routing#how-do-you-use-the-bus-to-route-things)

**Comment by mookid8000** [comment] 2016-05-12 15:14
I don't remember - what is the status of this one?

**Comment by dampee** [comment] 2016-05-12 15:47
The issue is still there.

To be honest, there are voices here asking whether we could replace Rebus. The estimation to remove Rebus from our application is probably lower than to rework our complete application (to be able to work with Rebus).

We know our code is broken(tm). :-) But we can't rewrite 5 years of development in a few months time.  
It's too bad this setup worked in v1.  It doesn't work in v2.

We will be discussing this over the next weeks.  Personally I would have a hard time with leaving Rebus, especially because I introduced rebus in the project.  But I am not the only one who flips the coin.

**Comment by mookid8000** [comment] 2016-07-15 12:00
I'll close this one for now. This was most likely just an issue with the usualy `async`-`await`-deadlock, which can occur in ASP.NET and WPF apps.

**Closed by mookid8000** 2016-07-15 12:00 UTC

**Comment by SGundl** [comment] 2016-12-19 03:40
Hello Guys,
I am also getting this issue This messaging entity has already been closed, aborted, or disposed.
Here is the scenario is, I am trying to process the Dead Letter Queue messages with Azure Functions.
Snippet here
deadLetterClient.OnMessage(msg =>
        {
            if (msg != null)
            {
                int retryCount = 0;
                string domainObjectID = string.Empty;
                domainObjectID = msg.GetBody<string>();
                try
                {
                        DateTime oTime = Convert.ToDateTime("ds");
                        msg.Complete();
                }
                catch (Exception error)
                {
						-- This is the error throwing some time.
						-- Error: This messaging entity has already been closed, aborted, or disposed
                        msg.Abandon(new Dictionary<string, object> { { "RetryCount", retryCount.ToString() } });
                }
            }
        });
        deadLetterClient.Close();

Some times it is working fine, but some times it is throwing "This messaging entity has already been closed, aborted, or disposed" error. But when I tested using console application, it is working fine.

**Comment by mookid8000** [comment] 2016-12-19 05:27
@SGundl are you using Rebus?

**Comment by SGundl** [comment] 2016-12-19 13:02
I am using Service Bus queues.

**Comment by mookid8000** [comment] 2016-12-19 13:51
@SGundl this is the Rebus issue tracker – while Rebus _can_ use Azure Service Bus (via the [Rebus.AzureServiceBus package](https://github.com/rebus-org/Rebus.AzureServiceBus/)), your question is not really relevant here.

You should probably post your question on [StackOverflow](http://stackoverflow.com/) (tagging it with something appropriate like ['azureservicebus'](http://stackoverflow.com/questions/tagged/azureservicebus)).

**Comment by SGundl** [comment] 2016-12-19 14:36
Thank you..

**Comment by mookid8000** [comment] 2016-12-19 22:23
You're welcome 😄 good luck 👍

**Comment by ashish051989** [comment] 2018-06-25 11:43
I'm getting timeout when ever I'm using Azure Service bus as one way client.... but as per implementation I need to use one way client only... any suggestions on that?
