### ISSUE TITLE
Redis transport integration

### ISSUE THREAD

**Issue by alessandro-chiavegato** [rebus-org/Rebus#1149] opened 2024-03-11 09:12 UTC
Hi,
I am interested in integrating Redis transport into Rebus.
Can i get support to do this?
Thanks.

Alessandro

**Comment by mookid8000** [comment] 2024-03-12 12:45
Does Redis provide durable message queues?

**Comment by alessandro-chiavegato** [comment] 2024-03-13 17:03
Hi, Redis provide two types of message queues, List and Stream. Messages can be persisted in memory and if you enabling AOF or RDB, messages can be backed up into the disk.

**Comment by AYss** [comment] 2024-03-13 17:43
I was experimenting with Redis as a transport for Rebus with Redis' pub/sub feature and also another scenario with SortedSet as a queue implementation. That was quite a long time ago, so I can tell you only general conclusion. Redis is not ment for this. Persistence, durability, delivery guarantees are concepts that are unknown to something that was designed to be a cache system. If Redis server instance failes, runs out of memory or something and backup shards fail too you can loose info and it is by design. This is cache thing. If it blows nothing bad happens. You just need to do few more calls to databases.

**Comment by mookid8000** [comment] 2024-03-14 08:09
@AYss  Thanks for chiming in. Your findings are very much in line with what I imagined 🙂 

@alessandro-chiavegato This does not mean that it can't work, but it probably means that you'll find yourself fighting unnecessary battles if you use Redis as a Rebus transport. Do you want to talk about maybe finding an alternative to Redis for your durable messaging needs?

**Comment by mookid8000** [comment] 2024-03-19 13:55
@alessandro-chiavegato  Closing, but feel free to continue the talk in here if you'd like to discuss alternative solutions

**Closed by mookid8000** 2024-03-19 13:55 UTC
