### ISSUE TITLE
Injecting scoped dependencies in pipeline steps

### ISSUE THREAD

**Issue by vegar** [rebus-org/Rebus#789] opened 2019-04-08 19:03 UTC
As far as I can see, step handlers are singletons. At least, in all examples I've seen, the step handler is instantiated and passed into the `PipelineStepInjector`s `OnSend` or `OnReceived`.

Now - I would like to use services from the IoC container during my step, and I guess that's why we get a `IResolutionContext` in the `Decorate` method. But as long as the pipeline step it self is a singleton, the injected service also becomes a singleton. 

I have a need for a scoped dependency. Each executed pipeline should have it's own instance of the service, and that instance should be shared within the scope of that pipeline. 

From what I can see, this is how services injected into the message handler itself works.

Am I missing something? Is there a way of resolving scoped services in the pipeline itself?

**Comment by mookid8000** [comment] 2019-04-08 19:58
Rebus uses [Injectionist](https://github.com/rebus-org/Injectionist) for its own DI needs, which is limited to simply providing a mechanism for Rebus to gradually build a configuration of services and decorators, which is then resolved when the bus is started.

As you've correctly found out, this means that everything exists only once. I guess you could say that every service has a "singleton lifestyle". 🙂 Although another way to look at it would be to consider it "scoped to the bus instance".

Once the bus has been built, Rebus does not use Injectionist for anything else. If you've configured Rebus to resolve message handlers in an IoC container, then of course that will be used, but that's it, really.

If your pipeline steps need to resolve dependencies to do their thing, and you want those instances to be scoped to the incoming message, I guess you could insert a step early in the pipeline that manages your IoC container scope (code written from my memory of things – might not compile 😉):
```csharp
.Options(o => o.Decorate<IPipeline>(c => {
	var step = new ContainerScopeStep(container);

	return PipelineStepInjector(c.Get<IPipeline>())
		.OnReceive(step, RelativePosition.After, typeof(SimpleRetryStrategyStep));
}))
```
where the step would then manage the scope:
```csharp
class ContainerScopeStep : IIncomingStep
{
	readonly IContainer _container;

	public ContainerScopeStep(IContainer container) => _container = container;

	public async Task(IncomingStepContext context, Func<Task> next)
	{
		using(var scope = _container.BeginScope())
		{
			context.Save(scope);
			await next();
		}
	}
}
```
The rest of the pipeline would then be able to retrieve the scope from the context and use it to resolve various services, e.g. like so:
```csharp
class AnotherPipelineStep : IIncomingStep
{
	public async Task(IncomingStepContext context, Func<Task> next)
	{
		// retrieve the current scope
		var scope = context.Load<IContainerScope>()
			?? throw new InvalidOperationException("Sorry!");

		// get a service
		var userRepository = scope.Resolve<IUserRepository>();

		// do stuff
		var user = await userRepository.FindAsync(...);

		await next();
	}
}
```
Would something like that work for you?

**Comment by vegar** [comment] 2019-04-08 20:50
Thanks. That might be an approach. I will investigate further. 

The actual use case is a variant of the identity flow thing that I've seen solved by using `Thread.CurrentPrincipal`. I might be wrong, but my impression is that `Thread.CurrentPrincipal` ain't used in .net core. I've also had trouble with the this kind of static values when it comes to async/await. So instead, I want to maintain a `principal accessor` through the ioc scope.

**Comment by mookid8000** [comment] 2019-04-09 07:30
> (...) my impression is that Thread.CurrentPrincipal ain't used in .net core

I think you're right about that.

**Comment by mookid8000** [comment] 2019-04-09 07:30
Closing this "issue" btw – we can keep the discussion going anyway, I'd like to know what you figure out

**Closed by mookid8000** 2019-04-09 07:30 UTC
Labels: Question

**Comment by vegar** [comment] 2019-04-09 08:15
I'm trying out your suggestion now. 
My concern is that this approach will give me a nested scope - the pipeline step belonging to one scope and the actual message handler belonging to another scope. That will break the purpose of this, since I want to initialize a principal accessor in the pipeline step and use it in the message handler.

**Comment by mookid8000** [comment] 2019-04-09 08:22
Which container are you using?

**Comment by vegar** [comment] 2019-04-09 08:25
The one built in to .net core.


________________________________
Fra: Mogens Heller Grabe <notifications@github.com>
Sendt: tirsdag, april 9, 2019 10:22 am
Til: rebus-org/Rebus
Kopi: Vegar Vikan; Author
Emne: Re: [rebus-org/Rebus] Injecting scoped dependencies in pipeline steps (#789)


Which container are you using?

**Comment by vegar** [comment] 2019-04-09 09:29
Suspicion confirmed: This approach will lead to the pipeline and message handler belonging to different scopes.

I guess the next step would be to make a new `DependencyInjectionHandlerActivator` that somehow reuse the scope from the pipeline instead of creating a new one. But is that possible? It doesn't look like the activator has access to anything but the message it self and the `ITransactionContext`. 

Or are you still able to access the incoming step context as described here: https://github.com/rebus-org/Rebus/wiki/Message-context ?

**Comment by mookid8000** [comment] 2019-04-09 15:06
Can argue with that! 🏖Have a nice vacation, I'll be here when you get back.

**Comment by vegar** [comment] 2019-04-25 09:36
I'm back! The new tanned and relaxed version of me came up with the following change to the activator:

https://github.com/vegar/Rebus.ServiceProvider/commit/10ff4fac67858a1abb6e377e1d2ea7789811bd72

Basically, checking the step context for an existing scope, and using that instead of creating a new one. This in combination with a step that creates (and disposes) the scope seems to solve my problem.

I had to copy the original activator and also the `AddRebus`-extensions to provide my modified activator. Is is an easier way of extending the current code - instead of having to replicate it?

**Comment by vegar** [comment] 2019-04-29 12:42
Now - what about outgoing steps...?

The outgoing step would also need access to the ioc container. Just like the incoming step, it needs to access the current principal from a ioc scoped service instead of `Thread.CurrentPrincipal`. 

When there is an outgoing message, it's either in the context of a message being handled, a request being handled, or anything else...

In the case of a message being handled, a scope is created in the incoming pipeline. In the case of a web request, asp.net ensures a new scope is created. In the last case, we cannot be sure there are any current scope... ...and most likely neither a current principal available...

Is there any way of getting this to work?

**Comment by mookid8000** [comment] 2019-04-29 13:15
The `OutgoingStepContext` has access to the `ITransactionContext` too, meaning that it too would be able to look up an active scope... a little bit involved, but definitely doable.

**Comment by vegar** [comment] 2019-04-29 13:43
so... 

What would you do?
Just use the `Thread.CurrentPrincipal` and hope the context doesn't die between async awaits..?

**Comment by ilcorvo** [comment] 2024-05-22 10:46
> If you look at [the code for the `GetHandlers` method](https://github.com/rebus-org/Rebus.ServiceProvider/blob/master/Rebus.ServiceProvider/DependencyInjectionHandlerActivator.cs#L35-L44), you can see that the method gets passed an `ITransactionContext`.
> 
> **That context actually contains a reference to the incoming step context, so it should be fairly easy to make the current scope available to steps following the one that resolves the handlers...**

Hi,
I need to save and get data into/from message header. Those data will be passed to a scoped service (`IPerRequestParamsService`) that can be used by message handlers.  
I looked at `DependencyInjectionHandlerActivator`: it creates a scope if it doesn't exist, but I'm not sure on how to get this working in my case:
- do I need to create a new step after `ActivateHandlersStep` and use the existing scope to resolve the `IPerRequestParamsService`? Is it not too late?
- or do I need to create a new step before `ActivateHandlersStep` to create a scope, resolve the `IPerRequestParamsService`, and then save the scope inside `transactionContext.Items[StepContext.StepContextKey]` ? Is it not violating the Rebus logic?
- or, probably, am I missing something that, out of the box, could help me in doing this?    

Thank you in advance.

**Comment by tystol** [comment] 2025-01-07 23:53
I'm having a similar problem. I have a custom `IOutgoingStep` and need to access the current microsoft DI `IServiceProvider` scope to resolve a particular scoped dependency. This works well using the `OutgoingStepContext.GetServiceScopeOrNull()` extension method when sending messages from within another Rebus handler (ie. getting access to the current incoming message scope created by Rebus.ServiceProvider package).
But when sending a message from an MVC controller, this extension method returns null.
Also, using `OutgoingStepContext.Load<IServiceProvider>()` in this scenario returns the root microsoft DI scope, not the current aspnet request scope.
How do I access the current aspnet request scope from a custom `IOutgoingStep`?

@mookid8000 sorry just tagging you incase you don't see this as the issue is closed.
