### ISSUE TITLE
Multiple Rebus buses in the same project sends to wrong queue

### ISSUE THREAD

**Issue by runes83** [rebus-org/Rebus#495] opened 2016-07-16 10:48 UTC
I have a project that uses two Rebus buses (both use AzureServiceBus) the main bus is the one used for all internal messages, and the external is for Events for external parties.

When sending with the externalbus I use             
            if (doesExternalAccountHaveAQueue))
                     await Bus.Advanced.Routing.Send(externalAccountGuid.ToString("n"), message); 
After I use this command messages I send on the main bus are now tried routet to this Bus (Azure Servicebus) but with the queuename of my internalbus so than it crashes.

I tried removing the external accounts queue from the database (no other changes to code or anything else) rerun the process and then it worked.

My theory is that there is a cache/static variable holding some ref to the externalqueue and then this happens. I have not tried wrapping the externalbus sending in it's own transaction context, could that be a tip ?

**Comment by mookid8000** [comment] 2016-07-16 20:39
How does it crash?

Could you maybe add a stack trace?

**Comment by runes83** [comment] 2016-07-17 11:39
It tries sending to the wrong queue (the wrong bus / Servicebus) and then i failes beacuse that Bus not have the queue that it is trying to send it to.

**Comment by mookid8000** [comment] 2016-07-17 16:30
oh.....I think I know what's wrong.... I'll try and reproduce it

My hypothesis is that Rebus' ambient transaction context from the first bus gets picked up when you send using the second bus, thus accidentally enlisting its work in the first bus' transaction context.

I'll be back when I know more 😄

**Comment by runes83** [comment] 2016-07-17 18:22
Thank you that would be great, having multiple buses in the same project is beginning to be a must have when we build Microservices on Rebus :-)

**Comment by mookid8000** [comment] 2016-07-18 07:24
My hypothesis turned out to be correct - thanks for reporting this error!

Due to dumb luck (or whatever) the error would potentially show only when a transport caches certain things in the transaction context.

Azure Service Bus transport does that because it caches all outgoing messages to be sent after the handler code has finished running.

And then it would only show if the two buses were configured to use separate Azure Service Bus namespaces.

The solution was to check if the ambient transaction context being picked up was one belonging to the bus.

**Comment by mookid8000** [comment] 2016-07-18 07:24
Thanks for reporting this issue!

It will be fixed in 0.99.68

**Closed by mookid8000** 2016-07-18 07:24 UTC
