### ISSUE TITLE
Separate configuration and starting of Bus

### ISSUE THREAD

**Issue by zabulus** [rebus-org/Rebus#457] opened 2016-05-23 07:11 UTC
First, let me introduce the structure of my app.
I have Autofac-based app with multiple modules. Modules are separated by buiseness entities. Entities are accessible through WCF services.
Application start consist of two main parts: 
- configuration where every module is being registered. Configuration part is modules itself, so it is separated in multiple files;
- starting part where every Autofac.IStartable components start, for example WCF services mentioned above. Starting part is a global start place, not only Autofac.IStartable mechanism, for example we have some components that should be manually started.

Now we added Rebus to connect several app instances in cluster, and we are using IBus as pub-sub transport. 

My concern is about following.
The app's configuration part hasn't changed, I've added all rebus stuff to the starting part. It motivated by interfaces of configuration adapter and RebusConfigurer: it uses constructed container not container builder. Now we have:
1. Bus configuration is placed in the starting part. But I'd like to have it in separate module.
2. All subscribing stuff for every module is placed in the starting part. That's most interesting, there is no possibility to predefine messages that a module will handle, it can be done only _after_ a bus is constructed. 

I can suggest solutions for above concerns, and even implement them. But I want to discuss them first.

**Comment by mookid8000** [comment] 2016-06-03 20:47
> 1. Bus configuration is placed in the starting part. But I'd like to have it in separate module

Hmm. I seem to recall some odd thing about Autofac's lifecycle being divided into separate "builder" and "container" phases.... is that what is tricking you?

IIRC the "problem" arises because Rebus would like to 

* register its `IBus` instance in the container (most naturally applies to the container builder phase of Autofac)
* look up handlers in the container (needs to use the resulting container, after it has been built)

Rebus' Autofac integration just circumvents this at the moment by using the `.Update(..)` function of the container builder to insert itself into the passed-in container.

I'm beginning to doubt that I even understand your problem.... can you maybe try and rephrase it?

> 2. All subscribing stuff for every module is placed in the starting part. That's most interesting, there is no possibility to predefine messages that a module will handle, it can be done only after a bus is constructed

Yeah, well - that's just how it is 😄 if you want all subscriptions to be in place before you start the first Rebus endpoint, you will need to establish them "behind the back" of Rebus somehow. If you're using SQL Server as the subscription storage, an easy way would be to simple insert the correct subscriptions in the subscription table in your production environment, possibly after having created the rows running Rebus during testing.

**Comment by zabulus** [comment] 2016-06-06 06:30
> Hmm. I seem to recall some odd thing about Autofac's lifecycle being divided into separate "builder" and "container" phases.... is that what is tricking you?

Yes that one.

> register its IBus instance in the container (most naturally applies to the container builder phase of Autofac)

You need IMessageHandler instances to start IBus?

> look up handlers in the container (needs to use the resulting container, after it has been built)

Does Rebus resolve a message handler on start or when message arrives?

> Yeah, well - that's just how it is :smile: if you want all subscriptions to be in place before you start the first Rebus endpoint, you will need to establish them "behind the back" of Rebus somehow. If you're using SQL Server as the subscription storage, an easy way would be to simple insert the correct subscriptions in the subscription table in your production environment, possibly after having created the rows running Rebus during testing.

Pls clarify this: Rebus receiving endpoint receives _only_ messages regarding to types placed in subscription storages or he recevies _all_ messages and filters them? As I understand it is first option: sender only sends messages to endpoints that handle a specified message type.

**Comment by mookid8000** [comment] 2016-06-06 07:11
> You need IMessageHandler instances to start IBus?

Yes - it is important that all handlers are ready to be resolved at the time you start the bus - otherwise, you could receive a message that could not be handled, or - much worse! - would be dispatched to only some of the handlers it was intended for.

> Does Rebus resolve a message handler on start or when message arrives?

When a message arrives, it resolves all handlers that it can be dispatched to.

> Rebus receiving endpoint receives only messages regarding to types placed in subscription storages or he recevies all messages and filters them? As I understand it is first option: sender only sends messages to endpoints that handle a specified message type.

The publisher looks up subscribers when it publishes an event. Therefore, subscribers only get events to which they have subscribed.

**Comment by zabulus** [comment] 2016-06-06 10:46
I understand that my concern is not really "problem", do get me wrong :) it's all perfectly works. It is just all about separation of concerns concept. I want message handlers and ```.HandleMessage<T>``` calls to be placed in same modules, not spread around my app.

**Comment by mookid8000** [comment] 2016-06-21 05:46
Hi @zabulus , I'm closing this issue as it is not really an issue 😁  we can still keep the talk going though, if you think there is something that could be done to make this better for you.

**Closed by mookid8000** 2016-06-21 05:46 UTC
