### ISSUE TITLE
Multiple Apps Using Same Input Queue - Exception Handler Sends Messages to All Apps

### ISSUE THREAD

**Issue by robpackwood** [rebus-org/Rebus#1050] opened 2022-08-29 13:46 UTC
The issue occurs when multiple instances of an application are running against the same input queue in RabbitMQ and an exception is thrown within a Rebus handler class. The message is handled by the 2nd instance of the application running against the same input queue, despite retry logic being disabled. For the same scenario, but where the handler does not throw an exception, everything works great, and the message is only handled once.

Sample code demonstrating the scenario and issue are here: 
[RebusHandlerException](https://github.com/robpackwood/RebusHandlerException)

**Comment by mookid8000** [comment] 2022-09-06 06:45
Unfortunately, this is "by design" with Rebus, because it needs to roll back the received message upon failure, thus making it visible in the queue again for other consumer instances to grab.

Since this particular topic has become more and more prominent (probably in proportion to the number of teams running competing consumers), I have decided that it is time to address it. It'll require that Rebus' internal worker loop is redesigned, but it should be feasible to do so before the end of year.

I'll try to create a spike next week and see how it goes - if things go well, it could also be much earlier.

**Comment by Qball1337** [comment] 2023-03-16 21:04
Any update on this issue or workaround?

**Comment by mookid8000** [comment] 2023-03-16 21:16
I’ve allocated a day next week to take a good, serious stab at refactoring this.  Stay tuned ☺️Sendt fra min iPhone–Mogens Heller GrabeTorsmark 48700 HorsensDanmark+45 ***@***.*** 16. mar. 2023 kl. 22.04 skrev Qball1337 ***@***.***>:﻿
Any update on this issue or workaround?

**Comment by mookid8000** [comment] 2023-03-21 13:44
OK here's a little progress report 🙂  Have worked today on changing some pretty central aspects of how the retry strategy works.

In master, the old `SimpleRetryStrategyStep` has been replaced by `DefaultRetryStrategyStep`, which reverses the order of operations. Where the old step would check the error tracker before trying to handle a message, the new step will optimistically try to handle the message and then perform whatever error strategy actions are required if it catches an exception.

Since it should be possible to forward the message being handled to the error queue, this made it necessary to figure out a way to "complete" the transaction context (in the sense that the incoming message is ACKed), but not "commit" it (i.e. send outgoing messages).

I feel I need to iterate some more on how the transaction context should work. 

Btw. it looks like the changes have resulted in a ~10% increase in dispatch performance, because the sunshine scenario no longer has to check a in-mem dictionary before handling the message. 😎

**Comment by robpackwood** [comment] 2023-03-21 13:50
Thanks for the update! I hope this makes it out soon. It will help reduce some errors we see with the retries occurring when we have the retries turned off.

**Comment by Qball1337** [comment] 2023-03-29 17:10
Thx for the update :)

**Comment by mookid8000** [comment] 2023-03-29 18:44
Ok I'm done working through all of the libs 🙂 next thing is that I will see if I can make a distributed error tracker that uses blobs to track delivery failures. 

Blobs are nice, because a cleanup policy can be configured, which will automatically delete blobs after a while, so that data will not pile up forever.

Next thing after that will be to make it possible for [Rebus Pro](https://pro.rebus.fm) customers to use Fleet Manager to track failed deliveries. Stay tuned 🙂

**Comment by mookid8000** [comment] 2023-03-31 10:55
I've just released Rebus.AzureBlobs 1.0.0-alpha02 to NuGet.org

It has a blob-based error tracker, which can be enabled by using the new `.Errors(..)` configuration branch, e.g. like this:

```csharp
services.AddRebus(
	configure => configure
		.Transport(...)
		.Errors(o => o.UseBlobStorage(..., "errors"))
);
```

It'll use an append blob + blob metadata to track delivery attempts and work like the default in-mem error tracker in every sense, except it'll allow sharing state between nodes in competing consumers scenarios.

**Comment by mookid8000** [comment] 2023-11-09 06:45
Closed, because this has been fixed in Rebus 8

**Closed by mookid8000** 2023-11-09 06:45 UTC
Labels: Backlog
