### ISSUE TITLE
Question about Transports and polling

### ISSUE THREAD

**Issue by bogdan-romaniv** [rebus-org/Rebus#961] opened 2021-03-18 10:18 UTC
Hello

I have been looking at examples of Rebus transports such as RabbitMq, Rebus.AzureServiceBus with the intention of seeing how to implement a transport on Sql Service Broker. But I have noticed that all these transports are poolling-base?.

I have been looking at these issues what you say about it

https://github.com/rebus-org/Rebus/issues/171

https://github.com/rebus-org/Rebus/issues/119

Any advice on how to implement this without the use of polling?

Thanks in advance

**Comment by mookid8000** [comment] 2021-03-18 13:11
What does it look like when receiving a message from service broker?

**Comment by sauron2k** [comment] 2021-03-22 10:29
In the subscriber side i basically connect to SQL Server and execute a WAITFOR statement in a loop

Something like this 

`WAITFOR( RECEIVE TOP (1)  
@Handle = conversation_handle,
@MessageType = message_type_name,
@Message = message_body FROM dbo.OrderQueue)`

In this specific project i need to get messages as soon as they enter the queue but i can't hammer the server with request every second. So that's why i need something more "push based".

**Comment by mookid8000** [comment] 2021-03-22 10:38
Ok, cool.

Btw. Rebus provides a way for you to configure back-off, so you can reduce the polling interval: https://github.com/rebus-org/Rebus/wiki/Back-off-strategy

This way, you can avoid hammering the server during idle periods.

**Comment by sauron2k** [comment] 2021-03-22 11:49
Yes i know and i'm using that a lot in other projects, the problem is that in this one i have some constraints: 

- I can only use MS-SQL 
- I need to process messages as soon as they get inserted in to the "queue"
- I cannot make indiscriminate calls to the server (aka i cannot poll)

I can use Service Broker directly but i was hoping to use Rebus because i expect to have a real queue in the near future and then the change will be painless.

I use Rebus a lot but i haven't take a deep look at its internals so i don't know if it's a lot of work to make a custom "subscriber" strategy.

**Comment by mookid8000** [comment] 2021-03-22 14:38
If I understand the service broker API correctly, it's still an ordinary SQL query sent to the server, right?

Because then I don't understand that it's a problem that Rebus' transport is "polling"... it's not more "polling" than what the transport implementation actually does, as it's asynchronous and `Task`-based: https://github.com/rebus-org/Rebus/blob/master/Rebus/Transport/ITransport.cs#L25

There's no limit to how long a call to `Receive` can wait before returning, as long as it respects the `CancellationToken` passed to it. So I would expect it to be possible to build a nice service broker-based transport for Rebus... don't you think?

**Comment by sauron2k** [comment] 2021-03-22 19:44
If there is no limit on waiting to receive data, then yes, it can be implemented.

I'm going to take a deeper look at the current implementations to see if I can go through with this by myself, but I would appreciate if you could give me any guidance on how to make a new transport.

**Comment by mookid8000** [comment] 2021-03-22 19:52
Sure thing! 🙂 

It's basically about implementing [`ITransport`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Transport/ITransport.cs)

You should end up being able to satisfy the transport tests from [Rebus.Tests.Contracts](https://www.nuget.org/packages/Rebus.Tests.Contracts/)

**Comment by mookid8000** [comment] 2021-12-07 08:06
Hi @bogdan-romaniv , did you get any further with this?

**Comment by mookid8000** [comment] 2022-04-04 08:28
I'll just close this one for now. Feel free to object, and then I'll reopen it 🙂

**Closed by mookid8000** 2022-04-04 08:28 UTC
Labels: Question
