### ISSUE TITLE
Dotnet Core Enlist Transaction 

### ISSUE THREAD

**Issue by brunobertechini** [rebus-org/Rebus#710] opened 2018-06-10 15:56 UTC
Hello there I was wondering how can I enlist a bus.publish operation in my currently existing transaction (im on dotnetcore / aspnetcore webapi method).

All my webapi methods are included in a UnitOfWork (transaction) enlisting EFCore DbContext operations.

The problem is if the entity fails to save bus.publish runs anyway.

I know that Rebus.TransactionScopes is designed for that but I saw it only has packages for NETFramework and not DotnetCore

Can you shed some light ?

Bruno

**Comment by mookid8000** [comment] 2018-06-10 19:53
Rebus has its own `RebusTransactionScope`, which is preferred over anything else, really, because it has an `async` complete method:

```csharp
using(var scope = new RebusTransactionScope())
{
    // the bus will enlist all of its actions in the scope in here
    // e.g.
    await bus.Publish(anEvent);
    // etc.
    // and then at the end of your uow:
    await scope.CompleteAsync();
}
```
But please remember that it's NOT possible to enlist two things in the same transaction and have the two transactions committed atomically.

What you can do is nest your database transaction and your Rebus transaction in a way that has the properties you're after.

If the database transaction is most likely to fail (I bet it is), then commit that one first, and then commit your Rebus transaction afterwards. That's usually how I do it.

**Closed by mookid8000** 2018-06-10 19:53 UTC

**Comment by brunobertechini** [comment] 2018-06-10 22:51
Actually this does not work as intended.

By calling scope.Complete() or CompleteAsync() messages are not being dispatched. 

If I call publish outside RebusTransactionScope it works fine

Bruno

**Comment by mookid8000** [comment] 2018-06-11 06:44
> Actually this does not work as intended.
>
> By calling scope.Complete() or CompleteAsync() messages are not being dispatched.

Any chance you can elaborate a little bit on what you are doing?

**Comment by brunobertechini** [comment] 2018-06-13 11:06
Sure, sorry for the lack of code.

I am integrating Rebus in aspnetboilerplate (www.aspnetboilerplate.com) which has its own UnitOfWork handling.

Right now, the solution I've found is to publish/send messages using Rebus upon the Abp UnitOfWorkCompleted event. This way I am sure my database transactions are commited. 

This only leads to any exception while trying to send/publish (like a message not mapped with r.TypeBased() ).

I would like to have a atomic transaction for my database operations and rebus messages inside a Application Service which is a weapi request.

**Comment by mookid8000** [comment] 2018-06-13 11:21
Ok, great 😄 if you can reproduce the issue, I will be happy to debug it.
